# Generated by Django 5.2.9 on 2025-12-03 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('due_date', models.DateTimeField(verbose_name='Data de Devolução Prevista')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução Real')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('RETURNED', 'Devolvido'), ('OVERDUE', 'Atrasado')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
