# Generated by Django 5.2.9 on 2025-12-08 05:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_alter_purchaserequest_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Prevista')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução Real')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('RETURNED', 'Devolvido'), ('OVERDUE', 'Atrasado')], default='PENDING', max_length=10, verbose_name='Status')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa')),
                ('fine_last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização da multa')),
                ('paid', models.BooleanField(default=False, verbose_name='Multa Paga')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
