# Generated by Django 5.2.9 on 2025-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Prevista'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('RETURNED', 'Devolvido'), ('OVERDUE', 'Atrasado')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
