# Generated by Django 6.0 on 2025-12-06 20:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Multa'),
        ),
        migrations.AddField(
            model_name='loan',
            name='fine_last_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização da multa'),
        ),
    ]
