# Generated by Django 5.2.8 on 2025-12-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=255, verbose_name='Editora')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('genre', models.CharField(max_length=50, verbose_name='Gênero')),
                ('language', models.CharField(max_length=50, verbose_name='Idioma')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Capa (Arquivo local)')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='Capa (URL externa)')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Total de Cópias')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Cópias Disponíveis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
