# Generated by Django 5.2.9 on 2025-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_purchaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20),
        ),
    ]
